import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  trainingSidebar: [{type: 'autogenerated', dirName: 'Training'}],
};

export default sidebars;
